#!/command/with-contenv bash

# Output starting message
s6-echo "Starting Unbound DNS server"

# Define service variables
NAME="unbound"
DESC="DNS server"
DAEMON="/usr/sbin/unbound"
PIDFILE="/run/unbound.pid"
HELPER="/usr/lib/unbound/package-helper"

# Ensure the Unbound daemon exists and is executable
if ! test -x "$DAEMON"; then
    exit 0
fi

# Default daemon options, can be overridden in /etc/default/unbound
DAEMON_OPTS=""

# Load custom options from /etc/default/unbound if it exists
if [ -f /etc/default/unbound ]; then
    . /etc/default/unbound
fi

# Setup chroot and update root trust anchor
$HELPER chroot_setup
$HELPER root_trust_anchor_update 2>&1 | logger -p daemon.info -t unbound-anchor

# Start the Unbound daemon with specified options
exec $DAEMON -d $DAEMON_OPTS