on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    #   - main/**
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

  - name: Docker meta
    id: meta
    uses: docker/metadata-action@v4
    with:
      # list of Docker images to use as base name for tags
      images: |
        ghcr.io/nickzelei/pihole-unbound
      # generate Docker tags based on the following events/attributes
      tags: |
        type=schedule
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=semver,pattern={{raw}}
        type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Set environment variables
    - run: echo VERSION=$(cat ./VERSION) >> $GITHUB_ENV

    # Build & Publish
    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./pihole-unbound
        push: true
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: ${{ steps.meta.outputs.tags }},ghcr.io/nickzelei/pihole-unbound:${{ env.VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/nickzelei/pihole-unbound-buildcache
        cache-to: type=registry,ref=ghcr.io/nucleuscloud/pihole-unbound-buildcache,mode=max

  release:
    runs-on: ubuntu-latest
    depends-on: deploy
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
