name: Build & Publish Docker Image to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - main/**

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    # Set environment variables
    - run: echo VERSION=$(cat ./one-container/pihole-unbound/VERSION) >> $GITHUB_ENV
    
    # Build & Publish
    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: peterlewis/pihole-unbound:latest, peterlewis/pihole-unbound:${{ env.VERSION }}
